name: Create Release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Set up Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x 

      - name: Build binaries
        run: task build:dist

      - name: Package binaries for release
        run: |
          for dir in dist/*; do
            if [ -d "$dir" ]; then
              platform=$(basename "$dir")
              (cd "$dir" && tar -czf "../../dist/teleconnect-${platform}.tar.gz" teleconnect)
            fi
          done
          
      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz